#!/usr/bin/env bash
source logging.sh
source datetime.sh

function man() {
cat << EOFMAN
 
  DESCRIPTION
    Fetches a file in the PATHs and displays its real path.
 
  USAGE: $ ${BASH_SOURCE[0]} file-name [OPTIONS]

  OPTIONS
    -h|--help : Displays this message.
      
    
EOFMAN
}

# -------------------
# Parse parameters
# -------------------
M_INPUTS=()  # many inputs for one option.
args=() # The arguments
while [ $# -ge 1 ]
do
    case "$1" in
        --debug)
          DBG=1
          ;;

        -h|--help)
          man && exit
          ;;

	-*)
	  log::exitError "Unrecognized option \"$1\"."
	  ;;

        *)
	  args+=("$1")
          shift
          ;;
    esac
    shift
done
set -euf

## Check file
_file="${args[0]}"
[ "$(type -t "$_file")" = "file" ] \
 || log::exitError "\"$_file\" is not a command file."

realpath $(type -p "$_file")
